name       : multipath-tools
version    : 0.5.0
release    : 5
source     :
    - http://christophe.varoqui.free.fr/multipath-tools/multipath-tools-0.5.0.tar.bz2 : f13cf1eb84e94e83b2019e68f7965526903c13e94246db43965d181668a0a6f9
license    : LGPL-2.0
summary    : Linux multipath tools
description: |
    Linux multipath tools
component  : system.utils
builddeps  :
    - pkgconfig(devmapper)
    - libaio-devel
build      : |
    %patch -p1 < $pkgfiles/add_find-multipaths.patch
    %patch -p1 < $pkgfiles/0015-shared-lock-for-udev.patch
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/0002-Use-stateless-file-system-locations-and-not-vendor-o.patch
    %make
install    : |
    %make_install LIB=%libdir%
    install -D -m 00644 $pkgfiles/multipath.conf $installdir/usr/share/defaults/multipath/multipath.conf
    rm -rf $installdir/etc/init.d
    rmdir $installdir/etc
