name       : multipath-tools
version    : 0.9.5
release    : 9
source     :
    - https://github.com/opensvc/multipath-tools/archive/refs/tags/0.9.5.tar.gz : e410fdee62ccaaecb79a0feb09c10d075a7254d013cf65543923bccb40c091c6
license    : LGPL-2.0
summary    : Linux multipath tools
description: |
    Linux multipath tools
component  : system.utils
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(json-c)
    - pkgconfig(liburcu)
    - libaio-devel
build      : |
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %make READLINE=libreadline LIB=%libdir%
install    : |
    %make_install DESTDIR=$installdir \
                  LIB=lib \
                  prefix="/usr"
