name       : multipath-tools
version    : 0.8.9
release    : 8
source     :
    - https://github.com/opensvc/multipath-tools/archive/refs/tags/0.8.9.tar.gz : 27a426facea0474e6dc48e026a94f7c86890d3f27b439b07ec26b0b9887b0cc4
license    : LGPL-2.0
summary    : Linux multipath tools
description: |
    Linux multipath tools
component  : system.utils
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(json-c)
    - pkgconfig(liburcu)
    - libaio-devel
build      : |
    #patch -p1 < $pkgfiles/add_find-multipaths.patch
    #patch -p1 < $pkgfiles/0015-shared-lock-for-udev.patch
    #patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    #patch -p1 < $pkgfiles/0002-Use-stateless-file-system-locations-and-not-vendor-o.patch
    #patch -p1 < $pkgfiles/0001-Link-with-proper-systemd.patch
    %make
install    : |
    %make_install LIB=%libdir%
    install -D -m 00644 $pkgfiles/multipath.conf $installdir/usr/share/defaults/multipath/multipath.conf
    rm -rf $installdir/etc/init.d
